[Settings]
  ID = "ba4c2d75-7e4c-40e0-84b6-161b58bf01b1"

[build]
  base = "."
  publish = ""
  command = ""

[context.production]
  publish = ""
  command = ""

[context.deploy-preview]
  publish = ""
  command = ""

[context.branch-deploy]
  publish = ""
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
